apiVersion: apps/v1
kind: Deployment
metadata:
  name: microshop
spec:
  selector:
    matchLabels:
      app: microshop
  template:
    metadata:
      labels:
        app: microshop
    spec:
      volumes:
        - name: postgres-host-path
          hostPath:
            path: /run/desktop/mnt/host/c/data/pgdata
            type: DirectoryOrCreate
      containers:
      - name: microshop-product-service
        image: microshop-product-service:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
      - name: rabbitmq
        image: rabbitmq:management
        imagePullPolicy: Always
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 5672
        - containerPort: 15672
      - name: postgres
        image: postgres
        volumeMounts:
          - mountPath: /var/lib/postgresql/data/pgdata
            name: postgres-host-path
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: adminer
        image: adminer
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      - name: fusionauth
        image: fusionauth/fusionauth-app:latest
        env:
          - name: DATABASE_URL
            value: jdbc:postgresql://localhost:5432/fusionauth
          - name: DATABASE_ROOT_USERNAME
            value: postgres
          - name: DATABASE_ROOT_PASSWORD
            value: postgres
          - name: DATABASE_USERNAME
            value: fusionauth
          - name: DATABASE_PASSWORD
            value: fusionauth
          - name: FUSIONAUTH_APP_RUNTIME_MODE
            value: development
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9011
